<?php
echo "<style>body{font-size:10px;}</style>";
echo "<table style='width:80%;'>";
echo "<tr>";
echo "<td>";
echo "<img src='images/mineduc.png' style='width: 150px; height: 70px;'>";
echo "</td>";
echo "<td><center>";
echo "<p style='font-size:12px;margin-top:0;margin-bottom:0;'>SUBSECRETARIA DE EDUCACIÓN ESPECIALIZADA E INCLUSIVA</p>";
echo "<p style='font-size:12px;margin-top:0;margin-bottom:0;'>DIRECCIÓN NACIONAL DE EDUCACIÓN PARA PERSONAS CON ESCOLARIDAD INCONCLUSA</p>";
echo "<p style='font-size:12px;margin-top:0;margin-bottom:0;'>FORMATO AUXILIAR DE NOTAS PARCIALES PARA ".strtoupper($oferta->nombre)." POR ASIGNATURA</p>";
echo "</center></td>";
echo "</tr>";
echo "</table>";

echo "<table>";
	echo "<tr>";
		echo "<td><label style='font-weight: bold; font-size: 12px;'>CÓGIGO AMIE:</label></td>";
		echo "<td><label>$ie->amie</label></td>";
		echo "<td><label style='font-weight: bold; font-size: 12px;'>INSTITUCIÓN EDUCATIVA:</label></td>";
		echo "<td><label>$ie->institucion</label></td>";
		echo "<td><label style='font-weight: bold; font-size: 12px;'>DISTRITO EDUCATIVO:</label> </td>";
		echo "<td><label>$ie->distrito</label></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td><label style='font-weight: bold; font-size: 12px;'>PERIODO LECTIVO:</label></td>";
		echo "<td><label>$oferta->periodo</label></td>";
		echo "<td><label style='font-weight: bold; font-size: 12px;'>GRADOS/NIVELES:</label></td>";
		echo "<td><label>8vo - 9no - 10mo E.G.B.</label></td>";
		echo "<td><label style='font-weight: bold; font-size: 12px;'>PARALELO:</label></td>";
		echo "<td><label>$paralelo</label></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td><label style='font-weight: bold; font-size: 12px;'>ASIGNATURA:</label></td>";
		echo "<td>".strtoupper($asignatura->nombre)."</td>";
		echo "<td><label style='font-weight: bold; font-size: 12px;'>DOCENTE:</label></td>";
		echo "<td>".strtoupper($docente->apellidos)." ".strtoupper($docente->nombres)."</td>";
		echo "<td></td>";
		echo "<td></td>";
	echo "</tr>";
echo "</table>";

echo "<center>";
	echo "<hr style='margin-bottom: 0;margin-top: 0;border: 1px solid silver'>";
	echo "<label style='font-weight: bold;'>ESTADOS DE LOS ESTUDIANTES:</label>";
	echo "<label><em>P</em> = PROMOVIDO</label>";
	echo "<label><em>NP</em> = NO PROMOVIDO</label>";
	echo "<label><em>D</em> = DESERTADO</label>";
	echo "<hr style='margin-bottom: 0;margin-top: 0;border: 1px solid silver'>";
	echo "<label style='font-weight: bold;'>EVALUACIÓN COMPORTAMIENTO (COM): </label>";
	echo "<label><em>A</em> = Muy Satisfactorio</label>";
	echo "<label><em>; B</em> = Satisfactorio</label>";
	echo "<label><em>; C</em> = Poco Satisfactorio</label>";
	echo "<label><em>; D</em> = Mejorable</label>";
	echo "<label><em>; E</em> = Insatisfactorio</label>";
echo "</center>";

echo "<table style='border-top: 1px solid silver;border-left: 1px solid silver;border-bottom: 1px solid silver;'>";
	echo "<tr>";
		echo "<th style='border-right: 1px solid silver;'>No</th>";
		echo "<th  style='border-right: 1px solid silver;'>ESTUDIANTE</th>";
		echo "<th  style='border-right: 1px solid silver;'>IDENT</th>";
		echo "<th colspan='9' style='text-align: center; border-right: 1px solid silver;'>QUIMESTRE 1 (Q1)";
			echo "<table>";
				echo "<tr>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>P 1</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>P 2</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>P 3</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>P 10/10</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>P 80%</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>Ex 10/10</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>Ex 20%</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>Q1</th>";
					echo "<th style='width:25px;text-align: center;border-top: 1px solid silver;'>COM</th>";
				echo "</tr>";
			echo "</table>";
		echo "</th>";
		echo "<th colspan='9' style='text-align: center;border-right: 1px solid silver;'>QUIMESTRE 2 (Q2)";
			echo "<table>";
				echo "<tr>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>P 1</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>P 2</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>P 3</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>P 10/10</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>P 80%</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>Ex 10/10</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>Ex 20%</th>";
					echo "<th style='width:25px;text-align: center; border-right: 1px solid silver;border-top: 1px solid silver;'>Q2</th>";
					echo "<th style='width:25px;text-align: center;border-top: 1px solid silver;'>COM</th>";
				echo "</tr>";
			echo "</table>";
		echo "</th>";
		echo "<th style='text-align: center;border-right: 1px solid silver;'>Sup</th>";
		echo "<th style='text-align: center;border-right: 1px solid silver;'>Rem</th>";
		echo "<th style='text-align: center;border-right: 1px solid silver;'>Gra</th>";
		echo "<th style='width:25px;text-align: center;border-right: 1px solid silver;'>FINAL</th>";
		echo "<th style='width:25px;text-align: center;border-right: 1px solid silver;'>EST</th>";
	echo "</tr>";
if (isset($estudiantes)){
	foreach ($estudiantes as $key => $mat){
		$loop = $key + 1;
		echo "<tr>";
			echo "<td style='width:20px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$loop</td>";
			echo "<td style='border-right: 1px solid silver;border-top: 1px solid silver;'>$mat->nombres_aspirantes</td>";
			echo "<td style='width:60px;border-right: 1px solid silver;border-top: 1px solid silver;'>$mat->cedula_identidad</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_1_parcial_1</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_1_parcial_2</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_1_parcial_3</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_1_promedio_parciales</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>".bcdiv($mat->quimestre_1_promedio_parciales * 0.80,'1',2)."</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_1_examen</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>".bcdiv($mat->quimestre_1_examen * 0.20,'1',2)."</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_1_final</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_1_comportamiento</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_2_parcial_1</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_2_parcial_2</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_2_parcial_3</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_2_promedio_parciales</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>".bcdiv($mat->quimestre_2_promedio_parciales * 0.80,'1',2)."</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_2_examen</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>".bcdiv($mat->quimestre_2_examen * 0.20,'1',2)."</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_2_final</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->quimestre_2_comportamiento</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->supletorio</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->remedial</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->gracia</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->nota_final</td>";
			echo "<td style='width:25px;border-right: 1px solid silver;border-top: 1px solid silver;text-align:center;'>$mat->estado</td>";
		echo "</tr>";
	}
}
echo "</table>";